name: Build FFmpeg

on: 
  push:
  workflow_dispatch:
  schedule:
    - cron: 0 0 * * *

jobs:
  build:
    runs-on: ubuntu-latest
    steps: 
    - name: Checkout FFmpeg code
      uses: actions/checkout@v2
      with:
        repository: hexahigh/FFmpeg

    - name: Add apt repos
      run: |
          sudo add-apt-repository universe

    - name: Install dependencies
      run: |
         sudo add-apt-repository universe
         sudo apt update
         sudo apt install -y \
         nasm \
         yasm \
         autoconf \
         automake \
         build-essential \
         cmake \
         git-core \
         libass-dev \
         libfreetype6-dev \
         libsdl2-dev \
         libtool \
         libva-dev \
         libvdpau-dev \
         libvorbis-dev \
         libxcb1-dev \
         libxcb-shm0-dev \
         libxcb-xfixes0-dev \
         pkg-config \
         texinfo \
         wget \
         zlib1g-dev \
         libx264-dev \
         libx265-dev \
         libopus-dev \
         libflac-dev \
         libmp3lame-dev \
         libfdk-aac-dev \
         libvpx-dev \
         libass-dev \
         libgnutls28-dev \
         libladspa-dev \
         libbluray-dev \
         libcaca-dev \
         libcdio-dev \
         libcodec2-dev \
         libdav1d-dev \
         libflite1-dev \
         libfontconfig1-dev \
         libfreetype6-dev \
         libfribidi-dev \
         libglslang-dev \
         libgme-dev \
         libgsm1-dev \
         libjack-jackd2-dev \
         libmysofa-dev \
         libopenjpeg5-dev \
         libopenmpt-dev \
         libpulse-dev \
         librabbitmq-dev \
         librist-dev \
         librubberband-dev \
         libshine-dev \
         libsnappy-dev \
         libsoxr-dev \
         libspeex-dev \
         libsrt-dev \
         libssh-dev \
         libsvtav1-dev \
         libtheora-dev \
         libtwolame-dev \
         libvidstab-dev \
         libwebp-dev \
         libxvidcore-dev \
         libzimg-dev \
         libzmq3-dev \
         libzvbi-dev \
         liblv2-dev \
         libomxil-bellagio-dev \
         libopenal-dev \
         libopencl-dev \
         libgl1-mesa-dev \
         libsdl2-dev \
         libsndio-dev \
         libjxl-dev \
         pocketsphinx-dev \
         librsvg2-dev \
         libmfx-dev \
         libdc1394-22-dev \
         libdrm-dev \
         libiec61883-dev \
         chromaprint-dev \
         frei0r-dev \
         libplacebo-dev \
         libsvtav1-dev


    - name: Build FFmpeg
      run: |
        ./configure \
        --prefix=/tmp/f_build \
        --ld="g++" \
        --enable-gpl \
        --disable-stripping \
        --enable-gnutls \
        --enable-ladspa \
        --enable-libaom \
        --enable-libass \
        --enable-libbluray \
        --enable-libbs2b \
        --enable-libcaca \
        --enable-libcdio \
        --enable-libcodec2 \
        --enable-libdav1d \
        --enable-libflite \
        --enable-libfontconfig \
        --enable-libfreetype \
        --enable-libfribidi \
        --enable-libglslang \
        --enable-libgme \
        --enable-libgsm \
        --enable-libjack \
        --enable-libmp3lame \
        --enable-libmysofa \
        --enable-libopenjpeg \
        --enable-libopenmpt \
        --enable-libopus \
        --enable-libpulse \
        --enable-librabbitmq \
        --enable-librist \
        --enable-librubberband \
        --enable-libshine \
        --enable-libsnappy \
        --enable-libsoxr \
        --enable-libspeex \
        --enable-libsrt \
        --enable-libssh \
        --enable-libsvtav1 \
        --enable-libtheora \
        --enable-libtwolame \
        --enable-libvidstab \
        --enable-libvorbis \
        --enable-libvpx \
        --enable-libwebp \
        --enable-libx265 \
        --enable-libxml2 \
        --enable-libxvid \
        --enable-libzimg \
        --enable-libzmq \
        --enable-libzvbi \
        --enable-lv2 \
        --enable-omx \
        --enable-openal \
        --enable-opencl \
        --enable-opengl \
        --enable-sdl2 \
        --disable-sndio \
        --enable-libjxl \
        --enable-pocketsphinx \
        --enable-librsvg \
        --enable-libmfx \
        --enable-libdc1394 \
        --enable-libdrm \
        --enable-libiec61883 \
        --enable-chromaprint \
        --enable-frei0r \
        --enable-libx264 \
        --enable-libplacebo \
        --enable-librav1e \

        make
        sudo make install

    - name: Release to GitHub
      uses: ncipollo/release-action@v1
      with:
        name: Latest Autobuild
        tag: latest_auto
        commit: main
        body: ${{ github.event.head_commit.message }}
        artifacts: "/tmp/f_build/ffplay, /tmp/f_build/ffprove, /tmp/f_build/ffmpeg,"
        prerelease: false
