name: Build FFmpeg

on: 
  push:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps: 
    - name: Checkout FFmpeg code
      uses: actions/checkout@v2
      with:
        repository: hexahigh/FFmpeg

    - name: Install libjxl
      run: |
          wget -O jxl.tar.gz https://github.com/libjxl/libjxl/releases/download/v0.8.2/jxl-debs-amd64-ubuntu-22.04-v0.8.2.tar.gz
          mkdir jxl
          tar -zxf jxl.tar.gz -C ./jxl
          sudo apt install -y ./jxl/*.deb

    - name: Install dependencies
      run: |
         sudo add-apt-repository universe
         sudo apt update
         sudo apt install -y \
         nasm \
         yasm \
         autoconf \
         automake \
         libaom-dev \
         build-essential \
         cmake \
         git-core \
         pkg-config \
         texinfo \
         wget \

    - name: Build FFmpeg
      run: |
        ./configure \
        --prefix=/tmp/f_build \
        --ld="g++" \
        --enable-gpl \
        --disable-stripping \
        --enable-libjxl \
        
        make
        sudo make install

    - name: Release to GitHub
      uses: ncipollo/release-action@v1
      with:
        name: Latest Autobuild
        tag: latest_auto
        commit: main
        body: ${{ github.event.head_commit.message }}
        artifacts: "/tmp/f_build/ffplay, /tmp/f_build/ffprove, /tmp/f_build/ffmpeg,"
        prerelease: false
