name: Build FFmpeg and dependencies

on: 
  push:
  workflow_dispatch:
  schedule:
    - cron: 0 0 * * *

jobs:
  build-libx264:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v2
      
    - name: Install dependencies
      run: sudo apt-get install -y autoconf automake build-essential libtool pkg-config nasm
      
    - name: Build libx264
      run: |
        git clone https://code.videolan.org/videolan/x264.git
        cd x264
        ./configure --enable-static --prefix="/tmp/f_build"
        make
        sudo make install
        
    - name: Upload a Build Artifact
      uses: actions/upload-artifact@v3.1.3
      with:
        name: libx264
        path: /tmp/f_build/lib/*

  build-libx265:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v2
      
    - name: Install dependencies
      run: sudo apt-get install -y autoconf automake build-essential libtool pkg-config cmake mercurial nasm

    - name: Build libx265
      run: |
        git clone https://bitbucket.org/multicoreware/x265_git.git
        cd x265_git/build/linux
        cmake -G "Unix Makefiles" -DCMAKE_INSTALL_PREFIX="/tmp/f_build" -DENABLE_SHARED:bool=off ../../source
        make
        sudo make install

    - name: Upload a Build Artifact
      uses: actions/upload-artifact@v3.1.3
      with:
        name: libx265
        path: /tmp/f_build/lib/*

  build-libvpx:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v2
      
    - name: Install dependencies
      run: sudo apt-get install -y autoconf automake build-essential libtool pkg-config yasm

    - name: Build libvpx
      run: |
        git clone https://chromium.googlesource.com/webm/libvpx
        cd libvpx
        ./configure --disable-examples --disable-unit-tests --enable-vp9-highbitdepth --as=yasm --prefix="/tmp/f_build"
        make
        sudo make install

    - name: Upload a Build Artifact
      uses: actions/upload-artifact@v3.1.3
      with:
        name: libvpx
        path: /tmp/f_build/lib/*

  build-libfdk-aac:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v2
      
    - name: Install dependencies
      run: sudo apt-get install -y autoconf automake build-essential libtool pkg-config

    - name: Build libfdk-aac
      run: |
        git clone https://github.com/mstorsjo/fdk-aac
        cd fdk-aac
        autoreconf -fiv
        ./configure --disable-shared --prefix="/tmp/f_build"
        make
        sudo make install

    - name: Upload a Build Artifact
      uses: actions/upload-artifact@v3.1.3
      with:
        name: libfdk-aac
        path: /tmp/f_build/lib/*

  build-libmp3lame:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v2
      
    - name: Install dependencies
      run: sudo apt-get install -y autoconf automake build-essential libtool pkg-config

    - name: Build libmp3lame
      run: |
        wget https://downloads.sourceforge.net/project/lame/lame/3.100/lame-3.100.tar.gz
        tar xzvf lame-3.100.tar.gz
        cd lame-3.100
        ./configure --enable-nasm --disable-shared --prefix="/tmp/f_build"
        make
        sudo make install

    - name: Upload a Build Artifact
      uses: actions/upload-artifact@v3.1.3
      with:
        name: libmp3
        path: /tmp/f_build/lib/*

  build-libopus:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v2
      
    - name: Install dependencies
      run: sudo apt-get install -y autoconf automake build-essential libtool pkg-config

    - name: Build libopus
      run: |
        wget https://archive.mozilla.org/pub/opus/opus-1.3.1.tar.gz
        tar xzvf opus-1.3.1.tar.gz
        cd opus-1.3.1
        ./configure --enable-static --prefix="/tmp/f_build"
        make
        sudo make install

    - name: Upload a Build Artifact
      uses: actions/upload-artifact@v3.1.3
      with:
        name: libopus
        path: /tmp/f_build/lib/*

  build-libvorbis:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v2
      
    - name: Install dependencies
      run: sudo apt-get install -y autoconf automake build-essential libtool pkg-config libogg-dev nasm

    - name: Build libvorbis
      run: |
        wget http://downloads.xiph.org/releases/vorbis/libvorbis-1.3.7.tar.gz
        tar xzvf libvorbis-1.3.7.tar.gz
        cd libvorbis-1.3.7
        ./configure --enable-static --prefix="/tmp/f_build"
        make
        sudo make install

    - name: Upload a Build Artifact
      uses: actions/upload-artifact@v3.1.3
      with:
        name: libvorbis
        path: /tmp/f_build/lib/*

  build-ffmpeg:
    needs: [build-libx264, build-libx265, build-libvpx, build-libfdk-aac, build-libmp3lame, build-libopus, build-libvorbis]
    runs-on: ubuntu-latest
    steps:
    - name: Checkout FFmpeg code
      uses: actions/checkout@v2
      with:
        repository: hexahigh/FFmpeg

    - name: Download libx264
      uses: actions/download-artifact@v2.1.1
      with:
        name: libx264
        path: /tmp/f_build/

    - name: Download libx265
      uses: actions/download-artifact@v2.1.1
      with:
        name: libx265
        path: /tmp/f_build/

    - name: Download libvpx
      uses: actions/download-artifact@v2.1.1
      with:
        name: libvpx
        path: /tmp/f_build/

    - name: Download libfdk-aac
      uses: actions/download-artifact@v2.1.1
      with:
        name: libfdk-aac
        path: /tmp/f_build/

    - name: Download libmp3
      uses: actions/download-artifact@v2.1.1
      with:
        name: libmp3
        path: /tmp/f_build/

    - name: Download libopus
      uses: actions/download-artifact@v2.1.1
      with:
        name: libopus
        path: /tmp/f_build/

    - name: Download libvorbis
      uses: actions/download-artifact@v2.1.1
      with:
        name: libvorbis
        path: /tmp/f_build_lib/

    - name: list lib directory
      run: ls /tmp/f_build_lib/

    - name: Install dependencies
      run: sudo apt-get install -y autoconf automake build-essential libtool pkg-config libogg-dev nasm yasm

    - name: Build FFmpeg
      run: |
        ./configure \
          --prefix=/tmp/f_build \
          --extra-ldflags="-L/tmp/f_build_lib/" \
          --enable-gpl \
          --enable-gnutls \
          --enable-nonfree \
          --enable-libx264 \
          --enable-libx265 \
          --enable-libvpx \
          --enable-libfdk-aac \
          --enable-libmp3lame \
          --enable-libopus \
          --enable-libvorbis 
        make
        sudo make install
        
    - name: Create Release
      id: create_release
      uses: actions/create-release@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        tag_name: ${{ github.ref }}
        release_name: Release ${{ github.ref }}
        draft: false
        prerelease: false

    - name: Upload Release Asset
      id: upload_release_asset
      uses: actions/upload-release-asset@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        upload_url: ${{ steps.create_release.outputs.upload_url }}
        asset_path: /tmp/f_build/bin/ffmpeg
        asset_name: ffmpeg
        asset_content_type: application/octet-stream


