name: Build FFmpeg

on: 
  push:
  workflow_dispatch:
  schedule:
    - cron: 0 0 * * *

jobs:
  build:
    runs-on: ubuntu-latest
    steps: 
    - name: Checkout FFmpeg code
      uses: actions/checkout@v2
      with:
        repository: hexahigh/FFmpeg

    - name: Add apt repos
      run: |
          sudo add-apt-repository universe

    - name: Install dependencies
      run: |
        sudo apt update
        sudo apt install -y \
          nasm \
          yasm \
          autoconf \
          automake \
          build-essential \
          cmake \
          git-core \
          libass-dev \
          libfreetype6-dev \
          libsdl2-dev \
          libtool \
          libva-dev \
          libvdpau-dev \
          libvorbis-dev \
          libxcb1-dev \
          libxcb-shm0-dev \
          libxcb-xfixes0-dev \
          pkg-config \
          texinfo \
          wget \
          zlib1g-dev \
          libx264-dev \
          libx265-dev \
          libopus-dev \
          libflac-dev \
          libmp3lame-dev \
          libfdk-aac-dev \
          libvpx-dev \
          libass-dev \
          libvmaf-dev \
          libjxl-dev

    - name: Build FFmpeg
      run: |
        ./configure \
          --prefix=/tmp/f_build \
          --ld="g++" \
          --enable-libvmaf \
          --enable-gpl \
          --enable-libass \
          --enable-nonfree \
          --enable-libx264 \
          --enable-libx265 \
          --enable-libvpx \
          --enable-libfdk-aac \
          --enable-libmp3lame \
          --enable-libopus \
          --enable-libvorbis \
          --enable-libjxl
        make
        sudo make install

    - name: Release to GitHub
      uses: ncipollo/release-action@v1
      with:
        name: Latest Autobuild
        tag: latest_auto
        commit: main
        body: ${{ github.event.head_commit.message }}
        artifacts: "/tmp/f_build/ffplay, /tmp/f_build/ffprove, /tmp/f_build/ffmpeg,"
        prerelease: false
