name: Build FFmpeg

on: 
  push:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps: 
    - name: Checkout FFmpeg code
      uses: actions/checkout@v2
      with:
        repository: hexahigh/FFmpeg

    - name: Set vars
      run: |
          git_hash=$(git rev-parse --short "$GITHUB_SHA")

    - name: Install libjxl
      run: |
          wget -O jxl.tar.gz https://github.com/libjxl/libjxl/releases/download/v0.8.2/jxl-debs-amd64-ubuntu-22.04-v0.8.2.tar.gz
          mkdir jxl
          tar -zxf jxl.tar.gz -C ./jxl
          sudo apt install -y ./jxl/*.deb

    - name: Install dependencies
      run: |
         sudo add-apt-repository universe
         sudo apt update
         sudo apt install -y \
         nasm \
         yasm \
         autoconf \
         automake \
         libaom-dev \
         build-essential \
         cmake \
         git-core \
         pkg-config \
         texinfo \
         wget 

    - name: Install libs
      run: |
          sudo apt install -y \
          libx264-dev \
          libx265-dev \
          libnuma-dev \
          libvpx-dev \
          libopus-dev \
          libdav1d-dev

    - name: Build FFmpeg
      run: |
        ./configure \
        --prefix=/tmp/f_build \
        --ld="g++" \
        --enable-gpl \
        --enable-nonfree \
        --disable-stripping \
        --enable-libjxl \
        --enable-libx265 \
        --enable-libx264 \
        --enable-libvpx \
        --enable-libopus \
        --enable-libdav1d
        
        make
        sudo make install

    - name: Create tag
      uses: actions/github-script@v5
      with:
        script: |
            github.rest.git.createRef({
              owner: context.repo.owner,
              repo: context.repo.repo,
              ref: 'refs/tags/auto_$git_hash',
              sha: context.sha
            })

    - name: Delete old release and tag
      continue-on-error: true
      uses: dev-drprasad/delete-tag-and-release@v1.0.1
      with:
        delete_release: true
        tag_name: latest_auto
        github_token: ${{ secrets.GITHUB_TOKEN }}

    - name: Release to GitHub
      uses: ncipollo/release-action@v1
      with:
        name: Autobuild
        tag: latest_auto
        commit: main
        body: ${{ github.event.head_commit.message }}
        artifacts: "/tmp/f_build/ffplay, /tmp/f_build/ffprove, /tmp/f_build/ffmpeg,"
        prerelease: false
